trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  repositoryName: 'shory9zeci/lagesio:test' 

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker connection'
    repository: $(repositoryName)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'